### ISSUE TITLE
Bug: Profile Image 

### ISSUE THREAD

**Issue by yujit2003** [devXprite/gitglance#10]
Profile Image is coming out of frame
I would love to work in this issue under GSSoc
Please assign this to me

![image](https://github.com/devXprite/gitglance/assets/97657345/7c6270bc-99aa-4b4e-92d5-c7e3f71d6ff3)

**Comment by devXprite** [comment]
@yujit2003 Thanks For Your Findings! I have assigned you the issue!

**Comment by yujit2003** [comment]
@devXprite can you please assign me this issue under GSSoc

**Comment by devXprite** [comment]
> @devXprite can you please assign me this issue under GSSoc

I Have already assigned you
