### ISSUE TITLE
Feature: Footer

### ISSUE THREAD

**Issue by yujit2003** [devXprite/gitglance#11]
A Proper Footer section For our Website

**Comment by SohamPatel0810** [comment]
Please assign to it

**Comment by shresthaPandit** [comment]
Hi @yujit2003 I have experience in working with Nextjs. Please assign this issue to me. I will build a good UI in nextjs for Footer Section of this website. 

Doubt: Please let me know what things ypu want in the footer section other than about and website/social media links.

**Comment by Piyush-linux** [comment]
Issue has already be resolved 
Closes #58
