### ISSUE TITLE
Feature: Login and Sign up Page

### ISSUE THREAD

**Issue by yujit2003** [devXprite/gitglance#12]
Implementing Login/Signup Page for our Website

**Comment by mohdjami** [comment]
Hi @yujit2003 , I can work on this issue and build the login/Signup page using Nextauth, supabase and Prisma ORM building a robust backend.

**Comment by shresthaPandit** [comment]
I can work collaboratively with @mohdjami  for improving the UI / frontend of the login page. Please assign this issue to both of us.
