### ISSUE TITLE
Quirky CSS icon appear

### ISSUE THREAD

**Issue by GitNinja-bcd** [devXprite/gitglance#13]
The CSS logo is crooked; it should be straight like other logos to appear attractive
![Screenshot 2024-05-10 234432](https://github.com/devXprite/gitglance/assets/158538244/f3616fbd-4c19-4c43-97db-0e1f0dbe686e)
<img width="365" alt="image" src="https://github.com/devXprite/gitglance/assets/158538244/69c47447-6575-4fb2-97d7-77fcf1c82942">

**Comment by Rauukr** [comment]
assign me this project as GSSOC'24 contribution and add level

**Comment by GitNinja-bcd** [comment]
Yes please add label and kindly assign me this issue.

**Comment by devXprite** [comment]
Hey @GitNinja-bcd , I've assigned you on this issue. Looking forward to seeing your contributions! 

Happy coding!!
