### ISSUE TITLE
[Feature]: Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [devXprite/gitglance#24]
### Description

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

### Why implement this feature?

By implementing this feature the Contributors will feel appreciated of their efforts and also the time to write the message manually is reduced as it is automated.

### Any additional information?

![image](https://github.com/devXprite/gitglance/assets/50082154/65282c5e-e852-4d7e-8bb9-55ad712c4757)

### Checklist

- [X] I have checked the existing issues and made sure that this is not a duplicate feature request form.

**Comment by devXprite** [comment]
Assigned @sanmarg 

It's really a good feature
