### ISSUE TITLE
[Bug]: Time is not IST

### ISSUE THREAD

**Issue by Rohitha-pudu** [devXprite/gitglance#28]
### Description

the time is not IST
![image](https://github.com/devXprite/gitglance/assets/116823590/e9bba2e9-7fc5-4e9e-9bae-913b186f096d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by subhadeeproy3902** [comment]
@devXprite Its a quick fix.

**Comment by devXprite** [comment]
> @devXprite Its a quick fix.

Do you want to work on this issue?

**Comment by subhadeeproy3902** [comment]
> > @devXprite Its a quick fix.
> 
> @subhadeeproy3902 Do you want to work on this issue?

yes assign me 
i am already working

**Comment by subhadeeproy3902** [comment]
sending a PR soon
