### ISSUE TITLE
Missing following and badges earned

### ISSUE THREAD

**Issue by Priya-49** [devXprite/gitglance#30]
In the profile page there is no information about following and badges earned. So I would like to add them to the website.Please assign this to me.

**Comment by subhadeeproy3902** [comment]
I would like to contribute to this repo too @devXprite . Please assign me this

**Comment by subhadeeproy3902** [comment]
ok i knew this ... but yet i searched the internet ! @devXprite . we cannot get badge data from any github api

**Comment by devXprite** [comment]
> ok i knew this ... but yet i searched the internet ! @devXprite . we cannot get badge data from any github api

Yes. Currently, achievement badges are in beta, so it may be possible in the future, but not at the moment.
