### ISSUE TITLE
[Bug]: [UI] Charts are not aligned properly in md sized screens

### ISSUE THREAD

**Issue by SaranshBangar** [devXprite/gitglance#38]
### Contact Details

saranshbangad@gmail.com

### Description

The pie charts shown in "Charts" and "Follow Up" section are not  aligned properly

![image](https://github.com/devXprite/gitglance/assets/114401238/e8405dea-09d3-45c6-af50-3ff7264f03e6)

### Any additional information?

I am a GSSoC contributor, please label this issue accordingly

### Steps to reproduce the bug.

Reduce the screen size to medium (<768px) and look at the "Charts" and "Follow Up" sections

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by devXprite** [comment]
Hey @SaranshBangar, I've assigned you on this issue. Looking forward to seeing your contributions!

Happy coding!!

**Comment by SaranshBangar** [comment]
Resolved in PR #39
