### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [devXprite/gitglance#41]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by devXprite** [comment]
Hey @suhanipaliwal , I've assigned you on this issue. Looking forward to seeing your contributions! 

Happy coding!!

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this issue.

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level as per gssoc guidelines on this issue.

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level on this issue as per gssoc guidelines.
