### ISSUE TITLE
[Feature]: Improving footer

### ISSUE THREAD

**Issue by YadlaMani** [devXprite/gitglance#58]
### Description

The footer given now is good but it has only plain text
i think it would be better if we have logos in the footer

### Why implement this feature?

![image](https://github.com/devXprite/gitglance/assets/133841094/6959cae6-2fc3-4c8e-b406-46ba005406a1)

### Checklist

- [X] I have checked the existing issues and made sure that this is not a duplicate feature request form.

**Comment by Piyush-linux** [comment]
I'm on it :+1:
