### ISSUE TITLE
Update Read me 

### ISSUE THREAD

**Issue by Varda003** [devXprite/gitglance#9]
I can add more about the project features and visualization making it more amazing also about graphs and chart generation.

**Comment by Varda003** [comment]
please assign this issue to me

**Comment by devXprite** [comment]
> please assign this issue to me

Sure @Varda003

**Comment by Varda003** [comment]
hello sir @devXprite  just mentioned by the maintainer @sanjay-kv. You need to assign label like GGSOC'24 to issue also add label of Level 1, 2, 3. Please or else my Pr won't be counted.
